### ISSUE TITLE
Comparison error

### ISSUE THREAD

**Issue by diff3** [Shushuda/GeForce-NOW-generator#1]
The lists from GeForce and Steam differ. Sometimes games contain characters not used by the other list so you need to do some cleaning before you compare. 

Otherwise great script, I was thinking of writing my own before I found yours!

best 
Diff3

**Comment by Shushuda** [comment]
Thanks! I will check that in my free time. My private Steam game list seemed to work fine, so I didn't catch these differences.

Heh, I've actually got mad when I discovered GeForce NOW app nor website couldn't provide a list by itself, so I made this script for private use, but figured I might as well upload it for others. I've thought of Flask-ifying it and deploying to my Heroku, but free time is scarce nowadays.
